### ISSUE TITLE
I think your code only supports the MMLU benchmark.

### ISSUE THREAD

**Issue by cloudyrider** [matthew-pisano/bergeron#1]
Your code only supports the MMLU benchmark. Would you be kind enough to plan to add the other benchmarks?

**Comment by matthew-pisano** [comment]
Right now it does only support the *MMLU*.  Luckily, I have designed the code to be very easily extensible.

In order to add another benchmark, all anyone has to do is to subclass the [src.benchmarks.Benchmark](https://github.com/matthew-pisano/Bergeron/blob/c3e4601b7fea56aa09763dc99887f7e72581140b/src/benchmarks.py#L8) class and override the following methods:

* `Benchmark.configs(cls)`
  * This method returns a list of all dataset *configs* (different subsets within each split).
* `Benchmark.format_question(self, question_id: int, split_name: str = "", n_shot=0, as_example=False)`
  * This method takes in a question id from the benchmark and formats it as a prompt.
* `Benchmark.evaluate_answer(self, question_id: int, model_response: str, split_name: str = "")`
  * This method takes in a question id and a model response and returns `True` if the model's response is considered correct and `False` otherwise.

We do plan to add other benchmarks, but in the meantime, it should hopefully be easy for anyone to add others.  Feel free to submit a pull request if you would like to contribute.

Thank you for taking a look!
